In [1]:
import pandas as pd
import pymysql
import numpy as np
import json
import tmdbsimple as tmdb
from tqdm.notebook import tqdm_notebook
import warnings
import glob
import gzip
import os
warnings.filterwarnings('ignore')

In [2]:
pd.options.display.float_format = '{:,.0f}'.format

In [3]:
with open('/Users/Peach/Documents/Dojo-env/dojo-env-setup/Stack4/Week2/Proj3P2/tmdbenc.json', 'r') as f:
    esvar = json.load(f)

In [4]:
tmdb.API_KEY = esvar['API_KEY']

In [5]:
MovieDf = pd.DataFrame(columns=['title', 'budget', 'revenue', 'certification'])

# Custom Funcitons

In [6]:
def read_and_fix_json(JSON_FILE):
    """Attempts to read in json file of records and fixes the final character
    to end with a ] if it errors.
    
    Args:
        JSON_FILE (str): filepath of JSON file
        
    Returns:
        DataFrame: the corrected data from the bad json file
    """
    try: 
        previous_df =  pd.read_json(JSON_FILE)
    
    ## If read_json throws an error
    except:
        
        ## manually open the json file
        with open(JSON_FILE,'r+') as f:
            ## Read in the file as a STRING
            bad_json = f.read()
            
            ## if the final character doesn't match first, select the right bracket
            first_char = bad_json[0]
            final_brackets = {'[':']', 
                           "{":"}"}
            ## Select expected final brakcet
            final_char = final_brackets[first_char]
            
            ## if the last character in file doen't match the first char, add it
            if bad_json[-1] != final_char:
                good_json = bad_json[:-1]
                good_json+=final_char
            else:
                raise Exception('ERROR is not due to mismatched final bracket.')
            
            ## Rewind to start of file and write new good_json to disk
            f.seek(0)
            f.write(good_json)
           
        ## Load the json file again now that its fixed
        previous_df =  pd.read_json(JSON_FILE)
        
    return previous_df

In [7]:
# Function to write to json

def write_json(new_data, filename): 
    """Appends a list of records (new_data) to a json file (filename). 
    Adapted from: https://www.geeksforgeeks.org/append-to-json-file-using-python/"""  
    
    with open(filename,'r+') as file:
        # First we load existing data into a dict.
        file_data = json.load(file)
        ## Choose extend or append
        if (type(new_data) == list) & (type(file_data) == list):
            file_data.extend(new_data)
        else:
             file_data.append(new_data)
        # Sets file's current position at offset.
        file.seek(0)
        # convert back to json.
        json.dump(file_data, file)

In [8]:
#Funciton to extract certification 

def gmwr(m_id):

    movie = tmdb.Movies(m_id)
    
    info = movie.info()
    
    releases = movie.releases()
    
    for c in releases['countries']:
        if c['iso_3166_1'] == 'US':
            info['certification'] = c['certification']
    return info

In [9]:
gmwr('tt0848228')

{'adult': False,
 'backdrop_path': '/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg',
 'belongs_to_collection': {'id': 86311,
  'name': 'The Avengers Collection',
  'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
  'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'},
 'budget': 220000000,
 'genres': [{'id': 878, 'name': 'Science Fiction'},
  {'id': 28, 'name': 'Action'},
  {'id': 12, 'name': 'Adventure'}],
 'homepage': 'https://www.marvel.com/movies/the-avengers',
 'id': 24428,
 'imdb_id': 'tt0848228',
 'original_language': 'en',
 'original_title': 'The Avengers',
 'overview': 'When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!',
 'popularity': 99.992,
 'poster_path': '/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
 'production_companies': [{'id': 420,
   'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
   'name': 'Marvel Studios',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'}],
 'release_date': '2012-04-25',
 'revenue': 1518815515,
 'runtime': 143,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'},
  {'english_name': 'Hindi', 'iso_639_1': 'hi', 'name': 'हिन्दी'},
  {'english_name': 'Russian', 'iso_639_1': 'ru', 'name': 'Pусский'}],
 'status': 'Released',
 'tagline': 'Some assembly required.',
 'title': 'The Avengers',
 'video': False,
 'vote_average': 7.708,
 'vote_count': 28574,
 'certification': 'PG-13'}

In [10]:
gmwr('tt0332280')

{'adult': False,
 'backdrop_path': '/qom1SZSENdmHFNZBXbtJAU0WTlC.jpg',
 'belongs_to_collection': None,
 'budget': 29000000,
 'genres': [{'id': 10749, 'name': 'Romance'}, {'id': 18, 'name': 'Drama'}],
 'homepage': 'http://www.newline.com/properties/notebookthe.html',
 'id': 11036,
 'imdb_id': 'tt0332280',
 'original_language': 'en',
 'original_title': 'The Notebook',
 'overview': "An epic love story centered around an older man who reads aloud to a woman with Alzheimer's. From a faded notebook, the old man's words bring to life the story about a couple who is separated by World War II, and is then passionately reunited, seven years later, after they have taken different paths.",
 'popularity': 48.303,
 'poster_path': '/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg',
 'production_companies': [{'id': 12,
   'logo_path': '/5ThIuO93vsk47oexKTSdfKEr7EC.png',
   'name': 'New Line Cinema',
   'origin_country': 'US'},
  {'id': 1565, 'logo_path': None, 'name': 'Avery Pix', 'origin_country': 'US'},
  {'id': 2605,
   'logo_path': None,
   'name': 'Gran Via Productions',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'}],
 'release_date': '2004-06-25',
 'revenue': 115603229,
 'runtime': 123,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'}],
 'status': 'Released',
 'tagline': 'Behind every great love is a great story.',
 'title': 'The Notebook',
 'video': False,
 'vote_average': 7.879,
 'vote_count': 10324,
 'certification': 'PG-13'}

## Reading in "csv.gz"

In [11]:
path = '/Users/Peach/Dropbox/Dojo-env/dojo-env-setup/Stack4/Week1/Proj3P1/IMDB_data/DataMain/'
path2 = '/Users/Peach/Dropbox/Dojo-env/dojo-env-setup/Stack4/Week1/Proj3P1/IMDB_data/DataSecondary/'

In [12]:
csv_files = glob.glob(os.path.join(path, "*.csv.gz"))
csv_files

['/Users/Peach/Dropbox/Dojo-env/dojo-env-setup/Stack4/Week1/Proj3P1/IMDB_data/DataMain\\akas.csv.gz',
 '/Users/Peach/Dropbox/Dojo-env/dojo-env-setup/Stack4/Week1/Proj3P1/IMDB_data/DataMain\\basics.csv.gz',
 '/Users/Peach/Dropbox/Dojo-env/dojo-env-setup/Stack4/Week1/Proj3P1/IMDB_data/DataMain\\ratings.csv.gz']

In [13]:
all_files = glob.glob(path)
dataframes = {}

for filename in csv_files:
    with gzip.open(filename, 'rt', encoding='utf-8') as file:
        df = pd.read_csv(file, index_col=None)
        file_name = os.path.splitext(os.path.basename(filename))[0]
        dataframes[file_name] = df

In [14]:
# Access the dataframes using their original file names
akas = dataframes['akas.csv']
basics = dataframes['basics.csv']
ratings = dataframes['ratings.csv']

In [15]:
akas

,Unnamed: 0,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,200877,tt0035423,39,Kate and Leopold,US,NaN,NaN,alternative spelling,0
1,200880,tt0035423,41,Kate & Leopold,US,NaN,imdbDisplay,NaN,0
2,471501,tt0062336,6,The Tango of the Widower and Its Distorting Mi...,US,NaN,imdbDisplay,NaN,0
3,541987,tt0069049,3,The Other Side of the Wind,US,NaN,imdbDisplay,NaN,0
4,729946,tt0088751,1,Attack of the B-Movie Monster,US,NaN,working,NaN,0
...,...,...,...,...,...,...,...,...,...
91199,35870560,tt9914942,5,Life Without Sara Amat,US,NaN,imdbDisplay,NaN,0
91200,35872238,tt9915872,4,The Last White Witch,US,NaN,imdbDisplay,NaN,0
91201,35872591,tt9916170,5,The Rehearsal,US,NaN,imdbDisplay,NaN,0
91202,35872607,tt9916190,6,Safeguard,US,NaN,imdbDisplay,NaN,0
91203,35872779,tt9916362,19,Coven,US,NaN,imdbDisplay,NaN,0

In [16]:
basics

,Unnamed: 0,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,33803,tt0034413,short,Youth Gets a Break,Youth Gets a Break,0,"2,001",NaN,20,Short
1,34803,tt0035423,movie,Kate & Leopold,Kate & Leopold,0,"2,001",NaN,118,"Comedy,Fantasy,Romance"
2,39545,tt0040241,short,Color Rhapsodie,Color Rhapsodie,0,"2,021",NaN,6,Short
3,43548,tt0044326,short,Abstronic,Abstronic,0,"2,021",NaN,6,Short
4,55758,tt0056840,short,Aufsätze,Aufsätze,0,"2,021",NaN,10,Short
...,...,...,...,...,...,...,...,...,...,...
1198072,9844609,tt9916544,short,My Sweet Prince,My Sweet Prince,0,"2,019",NaN,12,"Drama,Short"
1198073,9844642,tt9916610,short,Private Eye,Private Eye,0,"2,019",NaN,22,"Drama,Mystery,Sci-Fi"
1198074,9844679,tt9916692,tvMovie,Teatroteka: Czlowiek bez twarzy,Teatroteka: Czlowiek bez twarzy,0,"2,015",NaN,66,Drama
1198075,9844712,tt9916766,tvEpisode,Episode #10.15,Episode #10.15,0,"2,019",NaN,43,"Family,Game-Show,Reality-TV"
1198076,9844754,tt9916856,short,The Wind,The Wind,0,"2,015",NaN,27,Short

In [17]:
ratings

         Unnamed: 0     tconst  averageRating  numVotes
0                 0  tt0000001              6      1971
1                 1  tt0000002              6       263
2                 2  tt0000003              6      1816
3                 3  tt0000004              6       178
4                 4  tt0000005              6      2612
...             ...        ...            ...       ...
1309290     1309290  tt9916730              8        10
1309291     1309291  tt9916766              7        21
1309292     1309292  tt9916778              7        36
1309293     1309293  tt9916840              9         6
1309294     1309294  tt9916880              8         6

[1309295 rows x 4 columns]

### Specifications - Financial Data
Your stakeholder would like you to extract and save the results for movies that meet all of the criteria established in part 1 of the project (You should already have a filtered dataframe saved from part one as a csv.gz file)

As a proof-of-concept, they requested you perform a test extraction of movies that started in 2000 or 2001

Each year should be saved as a separate .csv.gz file

One function will add the certification (MPGG Rating) to movie.info

The other function will help you append/extend a JSON file with Python

In [18]:
YEARS_TO_GET = [2000,2001]

errors = [ ]

# Start of OUTER loop
for YEAR in tqdm_notebook(YEARS_TO_GET, desc='YEARS', position=0):
    #Defining the JSON file to store results for year
    JSON_FILE = f'{path}tmdb_api_results_{YEAR}.json'
    # Check if file exists
    file_exists = os.path.isfile(JSON_FILE)
    # If it does not exist: create it
    if file_exists == False:
    # save an empty dict with just "imdb_id" to the new json file.
        with open(JSON_FILE,'w') as f:
            json.dump([{'imdb_id':0}],f)
    #Saving new year as the current df
    df = basics.loc[ basics['startYear']==YEAR].copy()
    # saving movie ids to list
    movie_ids = df['tconst'].copy()
    # Load existing data from json into a dataframe called "previous_df"
    previous_df = pd.read_json(JSON_FILE)
    # filter out any ids that are already in the JSON_FILE
    movie_ids_to_get = movie_ids[~movie_ids.isin(previous_df['imdb_id'])]
    # INNER Loop
    for movie_id in tqdm_notebook(movie_ids_to_get,
                                  desc=f'Movies from {YEAR}',
                                  position=1,
                                  leave=True):
        try:
            # Retrieve then data for the movie id
            temp = gmwr(movie_id)  
            # Append/extend results to existing file using a pre-made function
            write_json(temp,JSON_FILE)
            # Short 20 ms sleep to prevent overwhelming server
            time.sleep(0.02)
            
        except Exception as e:
            errors.append([movie_id, e])
    final_year_df = pd.read_json(JSON_FILE)
    final_year_df.to_csv(f"{path}final_tmdb_data_{YEAR}.csv.gz", compression="gzip", index=False)
        
    print(f"- Total errors: {len(errors)}")

YEARS:   0%|          | 0/2 [00:00<?, ?it/s]

Movies from 2000:   0%|          | 0/22684 [00:00<?, ?it/s]

KeyboardInterrupt:

In [ ]:
    for movie_id in tqdm_notebook(movie_ids_to_get,
                                  desc=f'Movies from {YEAR}',
                                  position=1,
                                  leave=True):
        try:
            # Retrieve then data for the movie id
            temp = get_movie_with_rating(movie_id)  
            # Append/extend results to existing file using a pre-made function
            write_json(temp,JSON_FILE)
            # Short 20 ms sleep to prevent overwhelming server
            time.sleep(0.02)
            
        except Exception as e:
            errors.append([movie_id, e])

In [20]:
csv_files_movie = glob.glob(os.path.join(path, "*.csv.gz"))
csv_files_movie

['/Users/Peach/Dropbox/Dojo-env/dojo-env-setup/Stack4/Week1/Proj3P1/IMDB_data/DataMain\\akas.csv.gz',
 '/Users/Peach/Dropbox/Dojo-env/dojo-env-setup/Stack4/Week1/Proj3P1/IMDB_data/DataMain\\basics.csv.gz',
 '/Users/Peach/Dropbox/Dojo-env/dojo-env-setup/Stack4/Week1/Proj3P1/IMDB_data/DataMain\\ratings.csv.gz']

In [ ]:
dataframe_final = {}

for filename in final_csv_files:
    with gzip.open(filename, 'rt', encoding='utf-8') as file:
        df = pd.read_csv(file, index_col=None)
        file_name = os.path.splitext(os.path.basename(filename))[0]
        dataframe_final[file_name] = df

In [ ]:
final_2000 = dataframes['final_tmdb_data_2000.csv']
final_2001 = dataframes['final_tmdb_data_2001.csv']

In [ ]:
final_2000

In [ ]:
final_2001